- Dockerfile
- examples/emscripten/htdocs/worker.js
- patches/tinyemu/Makefile
Now files generated by emscripten can be named via "--build-arg JS_OUTPUT_NAME".
> emscripten: allow specifying filename

- tests/wazero/go.mod
- tests/wazero/go.sum
- tests/wazero/main.go
This updates [wazero](https://wazero.io/) to [1.0.0-rc.2](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-rc.2) which notably
* is the final release candidate before 1.0 next Friday.
* improves instantiation performance (startup time)
* passes `os` package tests defined by Go.
* no longer supports importing unnamed modules.
> deps: updates wazero to 1.0.0-rc.2

- README.md
- tests/wazero/go.mod
- tests/wazero/go.sum
- tests/wazero/main.go
This updates [wazero](https://wazero.io/) to [1.0.0](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0) which begins our compatibility promise.
On behalf of everyone in the community, I want to thank you for trying wazero before we became stable. We will not raise unsolicited pull requests anymore. That said, if any update gives you problems, please feel free to contact [us](https://wazero.io/community/) on slack or via a GitHub issue.
Finally, if you would like to share your work, feel free to update our [users page](https://github.com/tetratelabs/wazero/blob/main/site/content/community/users.md)!
> deps: updates wazero to 1.0.1

- README.md
- tests/wazero/go.mod
- tests/wazero/go.sum
- tests/wazero/main.go
This updates [wazero](https://wazero.io/) to [1.0.2](https://github.com/tetratelabs/wazero/releases/tag/v1.0.2) which improves compiler performance, supports non-blocking stdin, and fixes some glitches.
> deps: updates wazero to 1.0.2

- Dockerfile
- tests/test.sh
```
- Improved support for running x86_64 containers on WASI/browser (#59)
- Added example of WASI-on-browser (#59)
- Removed hack for `poll_oneoff` leveraging wasi-vfs 0.3.0 (#54), thanks to @kateinoigakukun
- Refactored wazero tests and updated wazero version (#23, #28), thanks to @codefromthecrypt
```
> Prepare for v0.3.0

- Dockerfile
```
- x86: support mapdir on wasi (#98)
- Fixed Dockerfile not to case cache miss when building a Wasm image with a custom name (#73)
```
> Prepare for v0.4.0

- cmd/init/main.go
- patches/bochs/Bochs/bochs/main.cc
- patches/tinyemu/tinyemu/temu.c
- patches/tinyemu/tinyemu/wasi.c
- tests/integration/wamr_test.go
- tests/integration/wasmedge_test.go
- tests/integration/wasmer_test.go
- tests/integration/wasmtime_test.go
- tests/integration/wazero_test.go
- tests/wazero/main.go
This commit allows sharing envvars from wasi runtime to the container.
```
$ wasmtime run --env AAA=hello --env BBB=world /app/out.wasm /bin/sh -c 'echo $AAA $BBB'
hello world
```
> wasi: Support sharing envvar to container

- Dockerfile
```
-  Initial support for networking with network stack running outside of the container (docs: [`./examples/networking`](https://github.com/ktock/container2wasm/tree/v0.5.0/examples/networking)) (#123)
-  WASI: Support sharing envvar to container (#118)
```
> Prepare for v0.5.0

- cmd/create-spec/main.go
#131 (`Failed to run frr with wasmtime: Can't create pid lock file /var/run/frr/watchfrr.pid (No such file or directory), exiting`)
> Do not mount tmpfs on /run

- .github/workflows/release.yml
`hub` has been deprecated: https://github.com/actions/runner-images/issues/8362
> ci: release: migrate from hub to gh

- cmd/c2w-net/main.go
- cmd/c2w/main.go
Fix: #155
Always specify platform flag to make the build run based on amd64 images.
Ideally we should support performing build on arm64,etc images but as of now wasi-sdk only supports amd64 linux only.
> c2w: specify build platform

- Dockerfile
```
- Add default `TERM=xterm` envvar (#148)
- c2w: Always specify platform flag to run the build based on amd64 images (#160)
```
> Prepare for v0.5.2

- Dockerfile
```
- Enabled to fetch and run container images on browser, without pre-conversion of the images (#200)
- Fixed `c2w-net` to use new wasmtime CLI syntax of wamstime >= 14 (#194)
```
> Prepare for v0.6.0

- cmd/create-spec/main.go
This commit fixes `create-spec` to allow processing nested image index and tries to fix #207 .
```console
$ mkdir /tmp/testimg2
$ crane pull --format=oci alpine:3.14 /tmp/testimg2/
$ cat /tmp/testimg2/index.json
{
"schemaVersion": 2,
"mediaType": "application/vnd.oci.image.index.v1+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"size": 1638,
"digest": "sha256:0f2d5c38dd7a4f4f733e688e3a6733cb5ab1ac6e3cb4603a5dd564e5bfb80eed"
}
]
}
...
$ buildx build --progress=plain --build-arg TARGETARCH=amd64 --build-arg TARGETPLATFORM=linux/amd64 --platform=linux/amd64 -f Dockerfile --build-context assets=. --output type=local,dest=/tmp/out --build-arg OUTPUT_NAME=out.wasm --build-arg LINUX_LOGLEVEL=0 --build-arg INIT_DEBUG=false /tmp/testimg2
...
#22 …
```
> `create-spec`: support images with nested index

- cmd/create-spec/main.go
#210
- fix platform to be correctly recognized
-  convert only container manifest
> create-spec: fix for indexed images

- Dockerfile
```
- Fixed error on conversion of images containing non-container manifest (#212)
```
> Prepare for 0.6.2

- cmd/create-spec/main.go
Fixes #222
This is needed to run sudo in container. In the future we can make it configurable like [Docker can](https://github.com/docker/cli/blob/297704984b5334eac3311c30c36133b8b22bda6a/man/docker-run.1.md?plain=1#L615).
> Allow new privileges in container

- extras/imagemounter/go.mod
- extras/imagemounter/go.sum
- extras/imagemounter/main.go
- extras/runcontainerjs/src/web/runcontainer.js
- extras/runcontainerjs/src/web/stack-worker.js
- tests/imagemounter-test/main.go
Performing gzip decompression in wasm looks very slow (56s for starting gcc:9.2.0 on chrome) and offloading it to JS seems to speed up this (15s for the same image on chrome).
> imagemounter: Decompress layers in JS wrapper

- patches/bochs/Bochs/bochs/wasm.cc
- patches/bochs/Bochs/bochs/wasm.h
- patches/tinyemu/tinyemu/fs.h
- patches/tinyemu/tinyemu/fs_disk.c
- patches/tinyemu/tinyemu/virtio.c
Currently (unimplemented) 9pfs's xattr returns ENOTSUP but `ls` (GNU coreutils) prints error message for this errno. This commit fixes this by using EOPNOTSUPP instead, for supressing the error message.
```
$ wasmtime --mapdir /test/dir/share::/tmp/share/ /app/out.wasm ls -al /test/dir/share/
ls: /test/dir/share/: Unknown error 524
ls: /test/dir/share/.: Unknown error 524
ls: /test/dir/share/a: Unknown error 524
total 0
d--------- 1 root root  0 Jan  1  1970 .
drwxr-xr-x 3 root root 60 Mar  7 09:45 ..
---------- 1 root root  3 Mar  7 09:05 a
```
> mapdir: use EOPNOTSUPP for xattr

- Dockerfile
```
- Fixed error printed by `ls` for accessing xattr (#245)
- Fixed `sudo` didn't work in container (#225)
- Fixed imagemounter to decompress layers in JS wrapper (#244)
- Fixed fd error on operations for mapped directories (#242)
```
> Prepare for v0.6.3

- Dockerfile
- patches/bochs/Bochs/bochs/cpu/msr.cc
- patches/bochs/bochsrc.template
This enables to run applications depend on recent features.
> Use pre-configured cpu model

- cmd/c2w-net/main.go
- tests/integration/utils/utils.go
Currently we get too verbose logs during initialization loop of c2w-net.
```
$ c2w-net --invoke -p localhost:8000:80 /tmp/out/httpd.wasm --net=socket
connecting to NW...
failed connecting to NW: dial tcp 127.0.0.1:1234: connect: connection refused
connecting to NW...
failed connecting to NW: dial tcp 127.0.0.1:1234: connect: connection refused
connecting to NW...
failed connecting to NW: dial tcp 127.0.0.1:1234: connect: connection refused
connecting to NW...
failed connecting to NW: dial tcp 127.0.0.1:1234: connect: connection refused
connecting to NW...
```
So this PR moves some logs to `debug` level and improves the log message:
```
$ c2w-net --invoke -p localhost:8000:80 /tmp/out/httpd.wasm --net=socket
waiting for NW initialization
```
> c2w-net: move some logs to debug level

- extras/c2w-net-proxy/go.mod
- extras/c2w-net-proxy/go.sum
- extras/imagemounter/go.mod
- extras/imagemounter/go.sum
- go.mod
- go.sum
- tests/wazero/go.mod
- tests/wazero/go.sum
gvisor-tap-vsock maintains dependencies of CI-related tools (e.g. golangci-lint) in a go.mod of a submodule [`github.com/containers/gvisor-tap-vsock/tools`](https://github.com/containers/gvisor-tap-vsock/tree/e5452d7e33cafaa94cb4409253d8afd89adcfc3e/tools). That submodule is used in their CI but we don't import nor use it so we can safely remove it from our dependency tree: https://github.com/ktock/gvisor-tap-vsock/commit/5f02d9ba79d4a54fd12ae74845999007f6514f2d
However a license scanning tool (FOSSA) wrongly detects some GPL v3.0 dependencies in that package (e.g. [1])
So, in order to pass that scanning, this PR explicitly removes the dependency of `github.com/containers/gvisor-tap-vsock/tools`.
[1] https://github.com/containers/gvisor-tap-vsock/blob/e5452d7e33cafaa94cb4409253d8afd89adcfc …
> Use forked gvisor-tap-vsock to remove an unused package from dependencies

- Dockerfile
Fixes #492
This PR bumps up and tests Debian bullseye.
Thanks @shiftyp for reporting the issue and suggesting the fix.
> Dockerfile: bump up debian to bullseye

- Dockerfile
Related to https://github.com/yomaytk/elfconv-demo/issues/3
On Safari, QEMU's AArch64 emulator fails to start with an error `RangeError: Maximum call stack size exceeded.` . I've found adding -fno-inline-functions can avoid this error so this commit applies this flag as a quick workaround. In the long term, we should find a way to fix this without the additional flags. There is also a similar issue found in the emscripten repo https://github.com/emscripten-core/emscripten/issues/17897
> aarch64: qemu: apply workaround for the stack size exceeded error on safari
